services:
  application:
    build:
      dockerfile: ./Dockerfile
      context: .
  ports:
    - 8000:5000

# HOW FIND DOCS?

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/PGDATA
      POSTGRES_DB: bucket_list
      volumes: 
        - ./data/postgres:/var/lib/postgres/data
        - ./db/bucket_list.sql:/docker-entrypoint-initdb.d/init.sql
      secrets:
       - db-root-password

secrets:
  db-root-password:
    file: ./secrets/db-root-password.txt