services:
  application:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8080:5000

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bucket_list
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/bucket_list.sql:/docker-entrypoint-initdb.d/init.sql
